added 4.1 upgrade doc
regen-network/regen-ledger pull request #1510
Opened 2022-09-30 09:56 UTC by kaustubhkapatral

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-09-30 10:00 UTC, anilCSE requested changes

2022-09-30 10:00 UTC, anilCSE commented on docs/validators/upgrades/v4.1-upgrade.md
> +cp ./build/regen $HOME/.regen/cosmovisor/upgrades/v4.1.0/bin
```suggestion
cp ./build/regen $HOME/.regen/cosmovisor/upgrades/v4.1.0/bin
$HOME/.regen/cosmovisor/upgrades/v4.1.0/bin/regen version # should be v4.1.2
```

2022-09-30 10:06 UTC, aleem1314 commented
Let's add an entry for v4.1 in upgrade [overview](https://github.com/regen-network/regen-ledger/blob/main/docs/validators/upgrades/README.md?plain=1#L7).

2022-09-30 10:36 UTC, anilCSE approved these changes
lgtm

2022-09-30 10:40 UTC, aleem1314 approved these changes
lgtm

2022-09-30 11:27 UTC, merged

2022-10-04 04:40 UTC, ryanchristo commented
@mergifyio backport release/v4.1.x