Update v4.1-upgrade.md
regen-network/regen-ledger pull request #1514
Opened 2022-10-01 05:11 UTC by anilCSE

## Description

Update `v4.1.2` version in upgrade docs

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-10-01 17:22 UTC, aleem1314 commented
Hmm. Not sure why we are getting commit hash for the local build, but goreleaser binary is showing `4.1.2` version.

2022-10-01 17:31 UTC, anilCSE commented
> Hmm. Not sure why we are getting commit hash for the local build, but goreleaser binary is showing `4.1.2` version.

We should probably change the version to 
```
VERSION := $(shell echo $(shell git describe --tags) | sed 's/^v//')
```

2022-10-02 05:47 UTC, kaustubhkapatral commented on docs/validators/upgrades/v4.1-upgrade.md
> +$HOME/.regen/cosmovisor/upgrades/v4.1.0/bin/version
```suggestion
$HOME/.regen/cosmovisor/upgrades/v4.1.0/bin/regen version
```

2022-10-02 05:49 UTC, kaustubhkapatral requested changes

2022-10-02 05:49 UTC, kaustubhkapatral commented on docs/validators/upgrades/v4.1-upgrade.md
> +$HOME/.regen/cosmovisor/upgrades/v4.1.0/bin/version
```suggestion
$HOME/.regen/cosmovisor/upgrades/v4.1.0/bin/regen version
```

2022-10-02 05:55 UTC, kaustubhkapatral approved these changes

2022-10-02 06:03 UTC, aleem1314 approved these changes

2022-10-02 19:39 UTC, merged

2022-10-05 02:50 UTC, ryanchristo commented
@mergifyio backport release/v4.1.x