Setup swagger docs
regen-network/regen-ledger pull request #164
Opened 2020-11-12 13:25 UTC by aleem1413

2020-11-16 16:44 UTC, amaurymartiny commented
As pointed out in https://github.com/regen-network/regen-ledger/issues/161#issuecomment-726075064, don't we need to add grpc-gateway annotations before generating swagger docs?

2020-11-16 17:05 UTC, anilCSE commented
> As pointed out in [#161 (comment)](https://github.com/regen-network/regen-ledger/issues/161#issuecomment-726075064), don't we need to add grpc-gateway annotations before generating swagger docs?

I think that can be addressed in a separate PR as well. The config file here includes endpoints from regen modules too, it will be just regenerating the swagger docs when we add those annotations.

2020-11-16 17:08 UTC, anilCSE commented
@aleem1413 since we have all the proto files from cosmos, can we include them in the script as well? Let's avoid copying/update cosmos' swagger file manually

2020-11-19 14:20 UTC, aleem1413 commented
> @aleem1413 since we have all the proto files from cosmos, can we include them in the script directly to generate cosmos' swagger? Let's avoid copying/update cosmos' swagger file manually.

@anilCSE We don't have cosmos proto files in the regen-ledger.

2021-02-03 15:34 UTC, anilCSE requested changes

2021-02-03 15:34 UTC, anilCSE commented on scripts/protoc-swagger-gen.sh
> +wget https://raw.githubusercontent.com/cosmos/cosmos-sdk/v0.40.0/client/docs/swagger-ui/swagger.yaml -P ./client/docs
@aleem1314 can you update this URL to 0.41? And regenrate the docs

2021-02-03 15:34 UTC, anilCSE commented on scripts/protoc-swagger-gen.sh
> +rm -rf ./tmp-swagger-gen
```suggestion
rm -rf ./tmp-swagger-gen

```

2021-02-03 15:34 UTC, anilCSE commented on client/docs/config.json
> +}
```suggestion
}

```

2021-02-03 15:49 UTC, anilCSE approved these changes

2021-07-30 20:12 UTC, ryanchristo reviewed
Looking good. A few comments and suggestions. Also, can we update the "Gaia REST" tag for the `node_info` endpoint. [Here](https://www.npmjs.com/package/swagger-combine#renaming-tags) is the `swagger-combine` documentation to do so.

2021-07-30 20:12 UTC, ryanchristo commented on client/docs/config.json
> +        "title": "Regen Ledger - REST and gRPC Gateway docs",
```suggestion
        "title": "Regen Ledger - REST and gRPC Gateway Documentation",
```

2021-08-02 11:22 UTC, aleem1314 commented on scripts/protoc-swagger-gen.sh
> +rm -rf ./tmp-swagger-gen
> Or maybe we download this file into the tmp-swagger-gen directory?

Make sense.

2021-08-02 17:29 UTC, ryanchristo approved these changes
LGTM

2021-08-02 23:36 UTC, merged