Add grpc gateway annotations
regen-network/regen-ledger pull request #183
Opened 2020-11-19 12:19 UTC by aleem1413

closes: #182

2020-11-19 13:08 UTC, amaurymartiny commented on proto/regen/data/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/data/v1alpha1/cids";
```suggestion
        option (google.api.http).get = "/regen/data/v1alpha1/cids/{cid}";
```

2020-11-19 13:08 UTC, amaurymartiny commented on proto/regen/data/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/data/v1alpha1/cids";
We need to do that, right? Most of the annotations lack this

2020-11-19 16:29 UTC, aaronc requested changes

2020-11-19 16:29 UTC, aaronc commented on third_party/proto/google/protobuf/any.proto
> +// Protocol Buffers - Google's data interchange format
We don't need this file

2020-11-19 16:29 UTC, aaronc commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/classinfo/{class_id}";
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/class_info/{class_id}";
```

2020-11-19 16:29 UTC, aaronc commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batchinfo/{batch_denom}";
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batch_info/{batch_denom}";
```

2020-11-19 16:29 UTC, aaronc commented on proto/regen/data/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/data/v1alpha1/cids/{cid}";
```suggestion
        option (google.api.http).get = "/regen/data/v1alpha1/{cid}";
```

2020-11-19 16:29 UTC, aaronc commented on proto/regen/data/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/data/v1alpha1/signers/{signer}";
```suggestion
        option (google.api.http).get = "/regen/data/v1alpha1/by-signer/{signer}";
```

2020-11-19 17:07 UTC, amaurymartiny approved these changes
would be cool to have 1 or 2 integration tests too, for a later PR

2020-11-26 14:06 UTC, anilCSE requested changes

2020-11-26 14:06 UTC, anilCSE commented on proto/regen/data/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/data/v1alpha1/{cid}";
```suggestion
        option (google.api.http).get = "/regen/data/v1alpha1/cids/{cid}";
```

2020-11-26 14:06 UTC, anilCSE commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/{batch_denom}/balances/{account}";
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/balances/{account}/{batch_denom}";
```
or 
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batch_info/{batch_denom}/balances/{account}";
```
or 
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batches/{batch_denom}/balances/{account}";
```

2020-11-26 14:06 UTC, anilCSE commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/supply/{batch_denom}";
@amaurymartiny is `batches` a correct usage here?
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batches/{batch_denom}/supply";
```

2020-11-26 14:06 UTC, anilCSE commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/supply/{batch_denom}";
if not, lets use `batch_info/{batch_denom}/supply`

2020-11-26 14:06 UTC, anilCSE commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/precision/{batch_denom}";
```suggestion
        option (google.api.http).get = "/regen/ecocredit/v1alpha1/batches/{batch_denom}/precision";
```

2021-02-01 08:33 UTC, blushi commented
@aleem1314 Now that the group module is merged, we will also need to add grpc gateway annotations to it.

2021-05-17 15:14 UTC, amaurym commented
It seems that this fails because of the custom code generator. Maybe we should fix it in the SDK first? ref: https://github.com/cosmos/cosmos-sdk/pull/9302

2021-07-06 11:44 UTC, amaurym commented on scripts/protocgen.sh
> +  go get github.com/aleem1314/grpc-gateway/protoc-gen-grpc-gateway2@v1.16.5-final 2>/dev/null
Thanks @aleem1314 for taking a look! I'm not sure it's worth to fork grpc-gateway. Maybe it's better to just remove our customer codegen for now.

2021-07-07 10:43 UTC, amaurym approved these changes
Yes, this is going in the right direction (unfortunately for now). Pre-approving.

We can also remove the `protoc-gen-go-cosmos2` folder.

2021-07-08 16:55 UTC, anilCSE commented on .codecov.yml
> +  - "scripts"
```suggestion
  - "scripts"
  
```

2021-07-08 16:55 UTC, anilCSE commented on proto/regen/data/v1alpha2/query.proto
> +    option (google.api.http).get = "/regen/data/v1alpha2/by-hash";
why are we using `v1alpha2` here? If we stick to this, update the documentation above.

2021-07-08 16:55 UTC, anilCSE commented on proto/regen/ecocredit/v1alpha1/query.proto
> +        option (google.api.http).get = "/regen/ecocredit/v1alpha1/class_info/{class_id}";
let's use either `-` or `_`. Looks like we are using both for word separation

2021-07-14 14:58 UTC, anilCSE approved these changes

2021-07-14 15:36 UTC, aaronc approved these changes

2021-07-14 16:53 UTC, merged