remove casttype
regen-network/regen-ledger pull request #264
Opened 2021-02-17 09:33 UTC by likhita-809

2021-02-17 15:25 UTC, blushi requested changes
Thanks @likhita-809, looks good overall, just left minor comments! Also you might wanna resolve the merge conflicts.

2021-02-17 15:25 UTC, blushi commented on x/group/server/msg_server.go
> +
```suggestion
```

2021-02-17 15:25 UTC, blushi commented on x/group/server/query_server.go
> +	it, err := s.getGroupMembers(ctx, groupID, request.Pagination)
I guess we could also just use `uint64` in the place of `group.ID` as param of `getGroupMembers`

2021-02-17 15:25 UTC, blushi commented on x/group/server/query_server.go
> +	it, err := s.getGroupAccountsByGroup(ctx, groupID, request.Pagination)
ditto use `uint64` in the place of `group.ID` in `getGroupAccountsByGroup`

2021-02-17 15:25 UTC, blushi commented on x/group/types.go
> +	*/
can we remove that?

2021-02-17 15:25 UTC, blushi commented on x/group/types.go
> +	*/
ditto

2021-02-17 17:43 UTC, robert-zaremba approved these changes
I like it - code easier to read! Please look at Marie comments.

2021-02-18 08:36 UTC, blushi approved these changes

2021-02-18 08:38 UTC, blushi commented
thanks @likhita-809, I'll merge this!
Please make sure to resolve the conversations from the review once you've addressed them ;)

2021-02-18 08:39 UTC, merged