feat(x/ecocredit): params ORM
regen-network/regen-ledger pull request #854
Opened 2022-03-07 22:34 UTC by technicallyty

## Description

refactors params to use ORM and new msg based gov params

Closes: #729 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-03-11 02:27 UTC, ryanchristo requested changes
Looking good although I don't think we should merge this until we are certain v0.46 will land in the next release and therefore I'm going to block this for now. We should at least wait until a beta release for Hambach.

We should probably discuss the fee lists on a product call and, if we want to support fee lists, whether they should be the same list. I'm not sure we do though.

Also, we should remove `proto/regen/ecocredit/v1/types.proto` as this only includes the `Params` proto message. Any reason for keeping it in this pull request?

2022-03-11 02:27 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
This is a new feature that we might need to further discuss on a product call. I think for now we want to have REGEN be the only token accepted for fees on our network.

2022-03-11 02:27 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
This is a new feature that we might need to further discuss on a product call. I think for now we want to have REGEN be the only token accepted for fees on our network.

2022-03-11 03:25 UTC, technicallyty commented on proto/regen/ecocredit/v1/tx.proto
> +  string fee_denom = 5;
the existing param for credit class fee is of type `Coins`, which is a list of coins 🤷🏻

2022-03-11 03:27 UTC, technicallyty commented on x/ecocredit/server/core/keeper_test.go
> +	accountKeeper 	*mocks2.MockAccountKeeper
hmm yeah this keeps happening to my IDE - anytime i make a change it says i need to `go mod tidy` and then doesnt run go fmt... does this happen to you?

2022-03-11 03:29 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  string fee_denom = 5;
Ah, you're right. Maybe this is ok then. For some reason I thought it was `Coin`.

2022-03-11 03:30 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
Overlooked how the param is currently set up.

2022-03-11 03:31 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
Same here. Overlooked how the param is currently set up.

2022-03-11 16:54 UTC, ryanchristo commented on x/ecocredit/server/core/keeper_test.go
> +	accountKeeper 	*mocks2.MockAccountKeeper
Hmmm... whitespace is fixed for me on save. Also, I'm running `make tidy` (`./scripts/go-mod-tidy-all.sh` under the hood).

2022-03-11 17:07 UTC, technicallyty commented on x/ecocredit/server/core/params.go
> +func (k Keeper) NewCreditType(ctx context.Context, req *core.MsgNewCreditTypeRequest) (*core.MsgNewCreditTypeResponse, error) {
changed https://github.com/regen-network/regen-ledger/pull/854/commits/a9d202f1533fe31f629575cfe2dc6185467a15e6

2022-03-11 18:03 UTC, technicallyty commented
> Also, we should remove `proto/regen/ecocredit/v1/types.proto` as this only includes the `Params` proto message. Any reason for keeping it in this pull request?


i was unsure if this was going to make it in the next release, so i left existing params in place. mostly wanted to introduce the new params API to see how folks like this. i think theres other ways to update params (one monotlithic update function with onofs, etc).

2022-03-26 22:37 UTC, ryanchristo reviewed
Unblocking this as it does not remove existing param functionality. I only reviewed the proto files to start. Looking ahead a bit, I'm not sure if the implementation should exist within the "core" directory but instead at the root level since the params are not specific to "core", i.e. we have a basket fees param.

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/state.proto
> +    option(cosmos.orm.v1alpha1.singleton) = {
```suggestion
// AllowlistEnabled determines if the credit class creator allowlist is enabled.
// When set to true, only the addresses in the AllowedClassCreator table can create
// credit classes. When set to false, any address is free to create credit classes.
message AllowlistEnabled {
    // This table is controlled via governance.
    option (cosmos.orm.v1alpha1.singleton) = {
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/state.proto
> +    };
```suggestion
// CreditClassFee is a valid coin denom and amount that may be used as the fee for
// credit class creation.
message CreditClassFee {
    // This table is controlled via governance.
    option (cosmos.orm.v1alpha1.table) = {
        id: 13,
        primary_key: {fields: "denom"}
    };
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/state.proto
> +    };
```suggestion
// BasketFee is a valid coin denom and amount that may be used as the fee for
// creating a basket.
message BasketFee {
    // This table is controlled via governance.
    option (cosmos.orm.v1alpha1.table) = {
        id: 14,
        primary_key: {fields: "denom"}
    };
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/state.proto
> +    string amount = 2;
```suggestion
    // denom is the denom of the fee required to create a credit class.
    string denom = 1;

    // amount is the amount of the fee required to create a credit class.
    string amount = 2;
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/state.proto
> +    string amount = 2;
```suggestion
    // denom is the denom of the fee required to create a basket.
    string denom = 1;

    // amount is the amount of the fee required to create a basket.
    string amount = 2;
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  rpc UpdateBasketFee(MsgUpdateBasketFeeRequest) returns (MsgUpdateBasketFeeResponse);
```suggestion
  // AddCreditType adds a new credit type. This message must be signed by the governance module.
  rpc AddCreditType(MsgAddCreditType) returns (MsgAddCreditTypeResponse);

  // ToggleAllowList toggles the allow list. This message must be signed by the governance module.
  rpc ToggleAllowList(MsgToggleAllowListRequest) returns (MsgToggleAllowListResponse);

  // UpdateAllowedCreditClassCreators updates the allow list of credit class creators. This message
  // must be signed by the governance module.
  rpc UpdateAllowedCreditClassCreators(MsgUpdateAllowedCreditClassCreatorsRequest) returns (MsgUpdateAllowedCreditClassCreatorsResponse);

  // UpdateCreditClassFee updates the list of allowed denoms and their amounts to be used as credit
  // class fees. This message must be signed by the governance module.
  rpc UpdateCreditClassFee(MsgUpdateCreditClassFeeRequest) returns (MsgUpdateCreditClassFeeResponse);

  // UpdateBasketFee updates the list of allowed denoms and their amounts to be used as basket
  // creation fees. This message must be signed by the governance module.
  rpc UpdateBasketFee(MsgUpdateBasketFeeRequest) returns (MsgUpdateBasketFeeResponse);
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  string fee_denom = 5;
Looks like this will need to be resolved with master now.

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
Given this is the message for add, I don't think we need to include "The credit types are immutable and cannot be deleted." Also this should either be plural (we are adding multiple credit types) or we should limit to one credit type at a time.

```suggestion
// MsgAddCreditTypes is the Msg/AddCreditTypes request type.
message MsgAddCreditTypes {
  // credit_types is a list of credit types to add.
  repeated CreditType credit_types = 1;

  // root_address is the address of the signer.
  // This MUST equal the address of the gov module for the tx to succeed.
  string root_address = 2;
}
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
```suggestion
// MsgToggleAllowListRequest is the Msg/ToggleAllowListRequest request type
message MsgToggleAllowListRequest {
  // root_address is the address of the signer.
  // This MUST equal the address of the gov module for the tx to succeed.
  string root_address = 1;

  // toggle is what the allow list will be set to.
  bool toggle = 2;
}
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +}
Might also be nice to consistently put root address first or last in these message.

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  // this MUST equal the address of the gov module for the tx to succeed.
```suggestion
  // root_address is the address of the signer.
  // This MUST equal the address of the gov module for the tx to succeed.
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  string root_address = 1;
```suggestion
// MsgUpdateCreditClassFeesRequest is the Msg/UpdateCreditClassFees request type
message MsgUpdateCreditClassFeesRequest {
  // root_address is the address of the signer.
  // This MUST equal the address of the gov module for the tx to succeed.
  string root_address = 1;
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +message MsgAddCreditTypeResponse {}
```suggestion
// MsgAddCreditTypesResponse is the Msg/AddCreditTypes response type.
message MsgAddCreditTypesResponse {}
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +message MsgUpdateCreditClassFeeResponse {}
```suggestion
// MsgUpdateCreditClassFeesResponse is the Msg/UpdateCreditClassFees response type
message MsgUpdateCreditClassFeesResponse {}
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +  string root_address = 1;
```suggestion
// MsgUpdateBasketFeesRequest is the Msg/UpdateBasketFees request type.
message MsgUpdateBasketFeesRequest {
  // root_address is the address of the caller.
  // This MUST equal the address of the gov module for the tx to succeed.
  string root_address = 1;
```

2022-03-26 22:37 UTC, ryanchristo commented on proto/regen/ecocredit/v1/tx.proto
> +message MsgUpdateBasketFeeResponse {}
```suggestion
// MsgUpdateBasketFeesResponse is the Msg/UpdateBasketFees response type.
message MsgUpdateBasketFeesResponse {}
```

2022-04-04 22:34 UTC, closed without merging